# config/services.yaml
parameters:
    # dossier pour les fichiers uploades par les agriculteurs
    documents_directory: '%kernel.project_dir%/public/uploads/documents'
    payment_proofs_directory: '%kernel.project_dir%/public/uploads/payment-proofs'

    # Google reCAPTCHA
    recaptcha_site_key: '%env(RECAPTCHA_SITE_KEY)%'
    recaptcha_secret_key: '%env(RECAPTCHA_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Service/DocumentService.php'
            - '../src/Service/EmailService.php'
            - '../src/Service/FileUploader.php'
            - '../src/Service/MessagerieService.php'
            - '../src/Service/UserService.php'

    App\Service\Weather\OpenWeatherClient:
        arguments:
            $apiKey: '%env(OPENWEATHER_API_KEY)%'
            $baseUrl: '%env(OPENWEATHER_BASE_URL)%'

    App\Service\TwoFactorAuthService:
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $mailer: '@mailer'
            $code2faRepository: '@App\Repository\Code2faRepository'
            $logger: '@logger'

    App\EventSubscriber\TwoFactorSubscriber:
        arguments:
            $tokenStorage: '@security.token_storage'
        tags:
            - { name: 'kernel.event_subscriber' }

    App\Service\FaceRecognitionService:
        arguments:
            $projectDir: '%kernel.project_dir%'
