parameters:
    documents_directory: '%kernel.project_dir%/public/uploads/documents'
    recaptcha_site_key: '%env(RECAPTCHA_SITE_KEY)%'
    recaptcha_secret_key: '%env(RECAPTCHA_SECRET_KEY)%'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    payment_proofs_directory: '%kernel.project_dir%/public/uploads/payment-proofs'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Services de l'application
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Service/DocumentService.php'
            - '../src/Service/EmailService.php'
            - '../src/Service/FileUploader.php'
            - '../src/Service/MessagerieService.php'
            - '../src/Service/UserService.php'

    # Service OpenWeather
    App\Service\Weather\OpenWeatherClient:
        arguments:
            $apiKey: '%env(OPENWEATHER_API_KEY)%'
            $baseUrl: '%env(OPENWEATHER_BASE_URL)%'

    # Service Face Recognition
    App\Service\FaceRecognitionService:
        arguments:
            $projectDir: '%kernel.project_dir%'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
