parameters:
    documents_directory: '%kernel.project_dir%/public/uploads/documents'
    recaptcha_site_key: '%env(RECAPTCHA_SITE_KEY)%'
    recaptcha_secret_key: '%env(RECAPTCHA_SECRET_KEY)%'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    payment_proofs_directory: '%kernel.project_dir%/public/uploads/payment-proofs'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Service/DocumentService.php'
            - '../src/Service/EmailService.php'
            - '../src/Service/FileUploader.php'
            - '../src/Service/MessagerieService.php'
            - '../src/Service/UserService.php'

    App\Service\Weather\OpenWeatherClient:
        arguments:
            $apiKey: '%env(OPENWEATHER_API_KEY)%'
            $baseUrl: '%env(OPENWEATHER_BASE_URL)%'

    App\Service\FaceRecognitionService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\EventListener\LocaleListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 20 }
